name: py35
channels:
  - bioconda
  - menpo
  - conda-forge
  - defaults
dependencies:
  - viennarna=2.4.11=py35hd28b015_0
  - chardet=3.0.4=py35_3
  - deap=1.2.2=py35hf8a1672_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - jpeg=9c=h14c3975_1001
  - libgcc-ng=7.3.0=hdf63c60_0
  - libtool=2.4.6=h14c3975_1002
  - pysocks=1.6.8=py35_2
  - requests=2.19.1=py35_1
  - stopit=1.1.2=py_0
  - tpot=0.9.5=py35_1
  - tqdm=4.23.4=py_0
  - update_checker=0.16=py_0
  - urllib3=1.23=py35_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h516909a_1004
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.12=h14c3975_1002
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - _tflow_180_select=1.0=gpu
  - _tflow_select=2.1.0=gpu
  - absl-py=0.2.2=py35_0
  - appdirs=1.4.3=py35_0
  - asn1crypto=0.24.0=py35_0
  - astor=0.6.2=py35_0
  - attrs=18.1.0=py35_0
  - automat=0.7.0=py35_0
  - backcall=0.1.0=py35_0
  - blas=1.0=mkl
  - bleach=1.5.0=py35_0
  - bokeh=0.13.0=py35_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2019.5.15=0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.8.24=py35_1
  - cffi=1.11.5=py35h9745a5d_0
  - click=6.7=py35h353a69f_0
  - cloudpickle=0.5.3=py35_0
  - constantly=15.1.0=py35_0
  - cryptography=2.2.2=py35h14c3975_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cupti=9.0.176=0
  - cycler=0.10.0=py35hc4d5149_0
  - cytoolz=0.9.0.1=py35h14c3975_1
  - dask=0.19.2=py35_0
  - dask-core=0.19.2=py35_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py35_0
  - distributed=1.23.2=py35_0
  - entrypoints=0.2.3=py35h48174a2_2
  - expat=2.2.5=he0dffb1_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gast=0.2.0=py35_0
  - glib=2.56.1=h000015b_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.11=h16798f4_2
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.12.1=py35hdbcaa40_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py35ha1f6525_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - heapdict=1.0.0=py35_2
  - html5lib=0.9999999=py35_0
  - hyperlink=18.0.0=py35_0
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py35_0
  - imageio=2.3.0=py35_0
  - incremental=17.5.0=py35head57c3_0
  - intel-openmp=2018.0.3=0
  - ipykernel=4.10.0=py35_0
  - ipython=6.4.0=py35_0
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - ipywidgets=7.2.1=py35_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.12.0=py35_1
  - jinja2=2.10=py35h480ab6d_0
  - jsonschema=2.6.0=py35h4395190_0
  - jupyter=1.0.0=py35_4
  - jupyter_client=5.2.3=py35_0
  - jupyter_console=5.2.0=py35h4044a63_1
  - jupyter_core=4.4.0=py35ha89e94b_0
  - keras=2.2.2=0
  - keras-applications=1.0.4=py35_1
  - keras-base=2.2.2=py35_0
  - keras-preprocessing=1.0.2=py35_1
  - kiwisolver=1.0.1=py35hcb1117a_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.2.1=hb9ed12e_0
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.6.0=hdbcaa40_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - locket=0.2.0=py35h170bc82_1
  - markdown=2.6.11=py35_0
  - markupsafe=1.0=py35h4f4fcf6_1
  - matplotlib=2.2.3=py35hb69df0a_0
  - mistune=0.8.3=py35h14c3975_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.1=py35h3010b51_0
  - mkl_random=1.0.1=py35h629b387_0
  - msgpack-python=0.5.6=py35h6bb024c_1
  - nbconvert=5.3.1=py35hc5194e3_0
  - nbformat=4.4.0=py35h12e6e07_0
  - nccl=1.3.5=cuda9.0_0
  - ncurses=6.1=hf484d3e_0
  - networkx=2.1=py35_0
  - ninja=1.8.2=py35h6bb024c_1
  - notebook=5.6.0=py35_0
  - numpy=1.14.5=py35hcd700cb_0
  - numpy-base=1.14.5=py35hdbf6ddf_0
  - olefile=0.45.1=py35_0
  - opencv=3.4.2=py35h6fd60c2_1
  - openssl=1.0.2s=h7b6447c_0
  - packaging=17.1=py35_0
  - pandas=0.23.3=py35h04863e7_0
  - pandoc=2.2.1=h629c226_0
  - pandocfilters=1.4.2=py35h1565a15_1
  - pango=1.42.3=h8589676_0
  - parso=0.2.1=py35_0
  - partd=0.3.8=py35h68187f2_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pillow=5.2.0=py35heded4f4_0
  - pip=10.0.1=py35_0
  - pixman=0.34.0=hceecf20_3
  - prometheus_client=0.2.0=py35_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - protobuf=3.6.0=py35hf484d3e_0
  - psutil=5.4.7=py35h14c3975_0
  - ptyprocess=0.6.0=py35_0
  - py-opencv=3.4.2=py35hb342d67_1
  - pyasn1=0.4.3=py35_0
  - pyasn1-modules=0.2.2=py35_0
  - pycparser=2.18=py35h61b3040_1
  - pydot=1.2.4=py35_0
  - pygments=2.2.0=py35h0f41973_0
  - pyopenssl=18.0.0=py35_0
  - pyparsing=2.2.0=py35h041ed72_1
  - pyqt=5.9.2=py35h751905a_0
  - python=3.5.5=hc3d631a_4
  - python-dateutil=2.7.3=py35_0
  - pytorch=0.4.0=py35hdf912b8_0
  - pytz=2018.5=py35_0
  - pywavelets=0.5.2=py35h53ec731_0
  - pyyaml=3.12=py35h46ef4ae_1
  - pyzmq=17.0.0=py35h14c3975_0
  - qt=5.9.6=h8703b6f_2
  - qtconsole=4.3.1=py35h4626a06_0
  - readline=7.0=ha6073c6_4
  - scikit-image=0.14.0=py35hf484d3e_1
  - scikit-learn=0.19.1=py35hbf1f462_0
  - scipy=1.1.0=py35hfc37229_0
  - send2trash=1.5.0=py35_0
  - service_identity=17.0.0=py35_0
  - setuptools=39.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35hf484d3e_0
  - six=1.11.0=py35h423b573_1
  - sortedcontainers=2.0.5=py35_0
  - sqlite=3.24.0=h84994c4_0
  - tblib=1.3.2=py35hf1eb0b4_0
  - tensorboard=1.10.0=py35hf484d3e_0
  - tensorflow=1.10.0=gpu_py35h566a776_0
  - tensorflow-base=1.10.0=gpu_py35h6ecc378_0
  - tensorflow-gpu=1.10.0=hf154084_0
  - termcolor=1.1.0=py35_1
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35had42eaf_0
  - tk=8.6.7=hc745277_3
  - toolz=0.9.0=py35_0
  - torchvision=0.2.1=py35_0
  - tornado=5.0.2=py35_0
  - traitlets=4.3.2=py35ha522a97_0
  - twisted=17.5.0=py35_0
  - wcwidth=0.1.7=py35hcd08066_0
  - webencodings=0.5.1=py35hb6cf162_1
  - werkzeug=0.14.1=py35_0
  - wheel=0.31.1=py35_0
  - widgetsnbextension=3.2.1=py35_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=hf484d3e_0
  - zict=0.1.3=py35_0
  - zlib=1.2.11=ha838bed_2
  - zope=1.0=py35_0
  - zope.interface=4.5.0=py35h14c3975_0
  - dlib=19.9=py35_0
  - pip:
    - biopython==1.73
    - cython==0.29.2
    - dask-glm==0.2.0
    - dask-ml==0.11.0
    - forgi==1.1
    - imutils==0.5.2
    - keras-tqdm==2.0.1
    - keras-vis==0.5.0
    - llvmlite==0.27.0
    - logging-exceptions==0.1.8
    - msgpack==0.5.6
    - multipledispatch==0.6.0
    - numba==0.42.0
    - pysster==1.2.0
    - scikit-mdr==0.4.4
    - seaborn==0.9.0
    - skrebate==0.6
    - torch==0.4.0
    - xgboost==0.81

